import uuid
import time


# Transaction class with attributes that uniquely details a transaction on the block. The transaction object is
# a funciton of a block. One of the core aspects of Blockchain.
class Transaction():

    def __init__(self, senderPublicKey, receiverPublicKey, amount, type):
        self.senderPublicKey = senderPublicKey
        self.receiverPublicKey = receiverPublicKey
        self.amount = amount
        self.type = type
        self.id = uuid.uuid1().hex
        self.timestamp = time.time()
        self.signature = ''

# Method that returns attributes of Transaction object in a dictionary
    def toJSON(self):
        return self.__dict__

# Method that maps signature generated by Wallet to empty string signature attribute of Transaction class

    def sign(self, signature):
        self.signature = signature